# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/cic_compiler/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/cic_compiler/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/cic_compiler/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/cic_compiler/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
