# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/inba2/Desktop/DDFPGA/TermProject/ddfpga-project/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
